### ISSUE TITLE
Define a REST API.

### ISSUE THREAD

**Issue by dumheter** [SEP-G5/Backend#4]
This task is about defining the REST API, not implementing it. Specify what functions it will have, and what response should come from them, and what information you need to give the functions.
See the wiki

**Comment by LionelJouin** [comment]
I suggest that we use the OpenAPI specification to define the API.
https://www.openapis.org/

**Comment by dumheter** [comment]
I will agree to that if you help me write it, @LionelJouin !

This is what I have so far:

Make a new transaction  
  * path: /new
  * type: POST
  * format: "application/json"
  * content: {TRANSACTION CONTENT}  
  * response ok: {accepted: true}
  * response fail: {accepted: false, error_msg: "msg..."}  

Get information about bike SN 
  * path: /info_id/<bike sn>
  * type: GET
  * format: -
  * data: -
  * response ok: {transaction0: {...}, transaction1: {...}, ...}
  * responese fail: {error_msg: "msg..."}  

Get information about a public key (address)
  * path: /info_pk
  * type: GET
  * format: "application/json"
  * data: {pk: "<PUBLIC KEY IN HEX FORMAT>"}
  * response ok: {transaction0: {...}, transaction1: {...}, ...}
  * responese fail: {error_msg: "msg..."}

Here is an example of three transaction, with the first one being a "register" transaction, and the following two are transfers of the same bike/SN.

```
Transaction:{ id: SN1337BIKE, timestamp: 1574250819, public_key_input: "None
", public_key_output: "5881b25d947ca4842c2cbec1697bbc9ce3da7d3fa9f688f2f5914
b1ac2bf17c6", signature: "da8833f4b107173987e665f6e2daef36e66f2c4f36facc79e7
38be6c5adcaeebe13ead8345c2c040de0713b52bdbcce2931914f15cf39de01152bc79856450
0d534e3133333742494b454329d55d000000005881b25d947ca4842c2cbec1697bbc9ce3da7d
3fa9f688f2f5914b1ac2bf17c6"}                                               
```

```
Transaction:{ id: SN1337BIKE, timestamp: 1574250819, public_key_input: "5881
b25d947ca4842c2cbec1697bbc9ce3da7d3fa9f688f2f5914b1ac2bf17c6", public_key_ou
tput: "85d23c7ff49ff8f64115cbe76075b9f225d1c028449a8b426591ffb3cbd7741b", si
gnature: "fdf44c5fe2ac8809c5b38ad6fd3173f81ea048097bd1f70921d22b6533f4825d8a
1f7f7247977e7118e997daf0b15817ac2c6461a81c567e48a0f1670f9a5f0a534e3133333742
494b454329d55d000000005881b25d947ca4842c2cbec1697bbc9ce3da7d3fa9f688f2f5914b
1ac2bf17c685d23c7ff49ff8f64115cbe76075b9f225d1c028449a8b426591ffb3cbd7741b"}
```

```
Transaction:{ id: SN1337BIKE, timestamp: 1574250819, public_key_input: "85d2
3c7ff49ff8f64115cbe76075b9f225d1c028449a8b426591ffb3cbd7741b", public_key_ou
tput: "20bae0c899527efd78ea0a08d3fa78711d23a5423774c6862a9ed38f33546e21", si
gnature: "6cbe0c55c0b4020e0c724b6187091f0cbf0c43ce82c2480f1f859788ccdcecb990
4c4a9ab41073c075ca7069fe580395adf6e9a5041de48becd82a717a9cac04534e3133333742
494b454329d55d0000000085d23c7ff49ff8f64115cbe76075b9f225d1c028449a8b426591ff
b3cbd7741b20bae0c899527efd78ea0a08d3fa78711d23a5423774c6862a9ed38f33546e21"}
```

**Comment by LionelJouin** [comment]
I will write the YAML

I don't understand what is SN (Get information about bike SN).

We need a function to get the transactions with a public key (We can filter in the frontend what are the bikes the user owns)
We can add a function to get the last transactions (with an offset and a limit)
And a function to get the peers might be required i think

**Comment by dumheter** [comment]
Bike SN is Bike serial number, the value that is supposed to uniquely idetify a bike.

I have updated my comment to be more precise and added the function where you can get transactions from a public key.

**Comment by LionelJouin** [comment]
Check this commit https://github.com/SEP-G5/Backend/commit/7bf57488761adebec18c0ffb9fa1f7aa79ecbd8b
There is [online tool](https://app.swaggerhub.com/home) to edit and see the specification, 
It is also possible to generate mock @bheftye 
The generation of code can be done using [generator tools](https://openapi-generator.tech/docs/generators.html), but I don't think we should use it.
