### ISSUE TITLE
Register Transaction

### ISSUE THREAD

**Issue by bheftye** [SEP-G5/Backend#60]
Data Used
```json
{
  "id": "123456",
  "publicKeyInput": null,
  "publicKeyOutput": "MTE5LDIzNiwyNDQsMTM5LDc1LDExMiwxMTMsNzYsMTU0LDE5NiwxMDksMjE3LDIyMSwxNzQsMTgsOTAsNzMsMjI0LDE5MSwxODEsMTE4LDI1NSw4NCwxMTMsOTksNTQsMjUzLDk1LDE5OCwxNjIsMjQ1LDE4NQ==",
  "signature": "MTkxLDExMiwxOTgsMTQyLDE0Niw1MSw5NCwxMjcsMjA0LDg3LDcxLDI1MSwyNDcsNjksMjA0LDQ3LDYyLDE5NywxMDUsMTUyLDEyOSwyMTQsNjUsMTcwLDgxLDgsODEsMjgsMjQ3LDQzLDI1MSwyMTMsMjQ3LDgwLDc3LDE5MSwyMCwyNDEsNzQsMTAwLDEwMywyMzksMTA3LDIyNCwxNjksMjQxLDY5LDI2LDQ0LDIwMSwxNTgsMjQ3LDIyOSwxNjEsMTAyLDE3Nyw2NywxMzAsNjUsMTUyLDE1LDI0NCwxMiwxMw==",
  "timestamp": 1576596350,
}
```
Response code 401
```json
{
  "msg": "could not create public key from input",
}
```

**Comment by dumheter** [comment]
In data used, the public key is 118 bytes long. However, the algorithm we use for key creation has a fixed public key size of 32 bytes.

So, I'm guessing the translation from bytes to base64 might be wrong?

**Comment by dumheter** [comment]
Wait, I used https://www.base64decode.net/ to take a look at what the data used contains, and it seems to be 32 bytes. So somewhere that turnes into 118 bytes. Hang on, I'll check.

**Comment by dumheter** [comment]
Okey, I now see what's going on. Consider our example public key,
```
OMCBCY+IfmAKlxehqiAbVdjMCCbkvecZKjfzBfLK1q8=
```
With yours
```
MTE5LDIzNiwyNDQsMTM5LDc1LDExMiwxMTMsNzYsMTU0LDE5NiwxMDksMjE3LDIyMSwxNzQsMTgsOTAsNzMsMjI0LDE5MSwxODEsMTE4LDI1NSw4NCwxMTMsOTksNTQsMjUzLDk1LDE5OCwxNjIsMjQ1LDE4NQ==
```
They are both base64 encoded. However, yours has encoded the following characters.
```
119,236,244,139,75,112,113,76,154,196,109,217,221,174,18,90,73,224,191,181,118,255,84,113,99,54,253,95,198,162,245,185
```
While we have encoded the actual values, (instead of the characters). Does that make sense, and do you understand what needs to be done?

**Comment by bheftye** [comment]
Yes, I will correct it with Lionel's help!
